//! EXL3 linears and routed experts as the Python engine's cuda/exl3 lays them out and launches them: the tile plan,
//! the "strips" word layout, the launch geometry of linear.cu / experts.cu, and the kernel symbols of our copies
//! (zig/kernels/cuda/glm53_exl3_{linear,experts}.cu, generated by tools/glm53/copy_exl3_kernels.py).
const std = @import("std");

pub const Codebook = enum(u8) { @"3inst" = 0, mcg = 1, mul1 = 2 };

/// linear.cu's DType codes (rot_in's x and the linear's y).
pub const DType = enum(c_int) { f16 = 0, bf16 = 1, f32 = 2 };

/// x3linear.LOADS default (35): bit 0 the transposed walk, bit 1 16-byte weight loads, bit 5 PDL launches.
pub const linear_loads: u32 = 35;

/// x3linear.plan: (K splits, warps a program) for a K x N layer, the shape's alone.
pub fn plan(k: usize, n: usize) [2]usize {
    const blocks: usize = 192;
    const min_tiles: usize = 8;
    const kt = k / 16;
    const nb = n / 128;
    var sk: usize = 1;
    var wk: usize = if (nb >= 64) 8 else 4;
    if (nb < 64) {
        while (nb * sk < blocks and sk < 64) sk *= 2;
    }
    while ((wk > 4 or sk > 1) and (kt % (sk * wk) != 0 or kt / (sk * wk) < min_tiles)) {
        if (wk > 4) {
            wk = 4;
        } else if (sk > 1) {
            sk /= 2;
        } else break;
    }
    return .{ sk, wk };
}

/// linear.cu vec_ok<K2>: 16-byte weight loads (not at 1 and 2 bits, whose steps are shuffled; up to 6 bits).
pub fn vecOk(k2: usize) bool {
    return !(k2 == 2 or k2 == 4) and k2 <= 12;
}

/// One EXL3 linear on the GPU: trellis words in "strips" ([N/128, K/16, 8, 4*K2] int32), fp16 suh [K] and svh [N].
pub const Linear = struct {
    words: u64,
    suh: u64,
    svh: u64,
    counters: u64, // int32 [8 * N/128], zero between launches (the split-K arrival counts)
    k: usize,
    n: usize,
    k2: usize, // half-bits a value (2 * bits)
    cb: Codebook,
    sk: usize, // K splits
    wk: usize, // warps a program

    pub fn tileWords(self: Linear) usize {
        return 4 * self.k2;
    }

    /// (words between k tiles, words between 128-column blocks) in the strips layout.
    pub fn strides(self: Linear) [2]i64 {
        const tw = self.tileWords();
        return .{ @intCast(8 * tw), @intCast((self.k / 16) * 8 * tw) };
    }

    pub fn wordBytes(self: Linear) usize {
        return self.k * self.n * self.k2 / 64 * 4;
    }
};

/// A formatted symbol, NUL-terminated in `buf`.
fn fmtZ(buf: []u8, comptime fmt: []const u8, args: anytype) ![:0]const u8 {
    const s = try std.fmt.bufPrint(buf[0 .. buf.len - 1], fmt, args);
    buf[s.len] = 0;
    return buf[0..s.len :0];
}

/// x3linear.groupable: 1 to 3 linears of one input in one launch (same K, width, codebook and warps).
pub fn groupable(lins: []const *const Linear) bool {
    if (lins.len < 1 or lins.len > 3) return false;
    const a = lins[0];
    for (lins) |l| if (l.k != a.k or l.k2 != a.k2 or l.cb != a.cb or l.wk != a.wk) return false;
    return true;
}

/// x3linear.strips on the host: trellis tiles [K/16, N/16] of `tile_bytes` each (4 * K2 int32 words) ->
/// [N/128, K/16, 8] tiles: each 128-column block's tiles in k order.
pub fn strips(out: []u8, in: []const u8, k: usize, n: usize, tile_bytes: usize) void {
    const kt = k / 16;
    const nt = n / 16;
    std.debug.assert(in.len == kt * nt * tile_bytes and out.len == in.len);
    for (0..kt) |i| for (0..nt) |j| {
        const src = (i * nt + j) * tile_bytes;
        const dst = (((j / 8) * kt + i) * 8 + j % 8) * tile_bytes;
        @memcpy(out[dst..][0..tile_bytes], in[src..][0..tile_bytes]);
    };
}

/// linear.cu's Job / Jobs / RotJobs, passed by value (__grid_constant__): the same field order and C alignment.
pub const Job = extern struct {
    xh: u64,
    t: u64,
    stride_k: i64,
    stride_nb: i64,
    svh: u64,
    bias: u64,
    y: u64,
    z: u64,
    counters: u64,
    y_dtype: c_int,
    n: c_int,
    sk: c_int,
    start: c_int,
};
pub const max_jobs = 3;
pub const Jobs = extern struct { j: [max_jobs]Job, n: c_int };
pub const RotJobs = extern struct { suh: [max_jobs]u64, xh: [max_jobs]u64 };

comptime {
    std.debug.assert(@sizeOf(Job) == 88 and @sizeOf(Jobs) == 272 and @sizeOf(RotJobs) == 48);
}

/// linear.cu launch_wk's dynamic shared memory: the warps' row sums, or the 16-byte loads' staging if larger.
pub fn linearSmem(wk: usize, m: usize, k2: usize, v: bool) usize {
    const red = wk * @min(m, 8) * 128 * 4;
    const stage = if (v) wk * 8 * 4 * k2 * 4 else 0;
    return @max(red, stage);
}

/// The transposed walk's row groups: G = 1 up to 8 rows, else 2 (linear.cu launch()).
pub fn linearG(m: usize) usize {
    return if (m <= 8) 1 else 2;
}

/// Mangled name of tf_exl3_linear::linear_kernel<K2, CB, WK, G, V>(Jobs, int, int) (cuobjdump -symbols).
pub fn linearSymbol(buf: []u8, k2: usize, cb: Codebook, wk: usize, g: usize, v: bool) ![:0]const u8 {
    return fmtZ(buf, "_ZN14tf_exl3_linear13linear_kernelILi{d}ELi{d}ELi{d}ELi{d}ELi{d}EEEvNS_4JobsEii", .{ k2, @intFromEnum(cb), wk, g, @intFromBool(v) });
}

pub const rot_in_symbol = "_ZN14tf_exl3_linear13rot_in_kernelEPKviNS_7RotJobsEi";

/// The linear_kernel instantiations the copy exports (copy_exl3_kernels.py LINEAR_K2 x CB 2 x WK 4, 8 x G 1, 2).
pub const linear_k2s = [_]usize{ 6, 8, 10, 16 }; // 16: the MTP layer's 8-bit dense projections

// -- routed experts (cuda/exl3/experts.py) ---------------------------------------------------------------------------

/// experts.py's tile settings (n tiles a block, warps, K splits, tiles in flight): GLM's gate/up and down.
pub const Tiles = struct { nt: usize, w: usize, sk: usize, pf: usize };
pub const glm_gateup: Tiles = .{ .nt = 8, .w = 4, .sk = 4, .pf = 1 };
pub const glm_down: Tiles = .{ .nt = 8, .w = 4, .sk = 1, .pf = 1 };

/// experts.default_config: GLM's setting where it divides, else the next that does.
pub fn defaultTiles(k: usize, n: usize, gateup: bool) !Tiles {
    const cands = [_]Tiles{ if (gateup) glm_gateup else glm_down, .{ .nt = 8, .w = 4, .sk = 2, .pf = 1 }, .{ .nt = 8, .w = 4, .sk = 1, .pf = 1 }, .{ .nt = 4, .w = 4, .sk = 2, .pf = 2 }, .{ .nt = 4, .w = 4, .sk = 1, .pf = 2 } };
    for (cands) |c| if (k % (16 * c.sk * c.w) == 0 and n % (16 * c.nt) == 0) return c;
    return error.NoTileSetting;
}

/// experts_grouped.cuh's Epi (the fused epilogues), passed by value.
pub const Epi = extern struct {
    fuse: c_int = 0,
    pick: u64 = 0,
    e: c_int = 0,
    svh_g: u64 = 0,
    svh_u: u64 = 0,
    suh_d: u64 = 0,
    xd: u64 = 0,
    limit: f32 = 0,
    act_mode: c_int = 1,
    svh_d: u64 = 0,
    y: u64 = 0,
    wts: u64 = 0,
    out: u64 = 0,
    sy: u64 = 0,
    done: u64 = 0,
};

comptime {
    std.debug.assert(@sizeOf(Epi) == 112);
}

/// grouped_launch's K2 range template arguments (LO, HI) for a (min, max) half-bit range.
pub fn k2Range(lo: usize, hi: usize) [2]usize {
    if (lo == 8 and hi == 8) return .{ 8, 8 };
    if (lo >= 2 and hi <= 10) return .{ 2, 10 };
    return .{ 2, 16 };
}

/// tf_exl3x::grouped_kernel<CB, 8, 4, 1, 1, LO, HI> (GLM tiles, 16-byte loads one step ahead).
pub fn groupedSymbol(buf: []u8, cb: Codebook, lo: usize, hi: usize) ![:0]const u8 {
    return fmtZ(buf, "_ZN8tf_exl3x14grouped_kernelILi{d}ELi8ELi4ELi1ELi1ELi{d}ELi{d}EEEvPK6__halfS3_PKlS5_PKiS7_S7_S7_S7_PfiiiiiiiNS_3EpiE", .{ @intFromEnum(cb), lo, hi });
}

pub const group_symbol = "_ZN10tf_exl3x_k12group_kernelEPKiPiS2_S2_iiii";
pub const expert_rot_in_symbol = "_ZN10tf_exl3x_k13rot_in_kernelI13__nv_bfloat16EEvPKT_iPKiPK6__halfS9_PS7_SA_iii";
pub const gateup_epilogue_symbol = "_ZN10tf_exl3x_k22gateup_epilogue_kernelEPKfPKiPK6__halfS6_S6_PS4_iiiifi";

/// experts.py ACT_F32: fused.experts_part calls routed() with the default fp32 SwiGLU, no limit.
pub const act_f32: c_int = 1;

// -- Phase 3a: the prompt path (x3prefill.matmul's weight decode, prompt_experts.cu) -------------------------------

/// tf_exl3_linear::unpack_kernel<K2, CB>(const uint32_t*, half*, int, int64_t, int64_t): W_q [K, N] fp16.
pub fn unpackSymbol(buf: []u8, k2: usize, cb: Codebook) ![:0]const u8 {
    return fmtZ(buf, "_ZN14tf_exl3_linear13unpack_kernelILi{d}ELi{d}EEEvPKjP6__halfill", .{ k2, @intFromEnum(cb) });
}

/// prompt_experts.cu (tf_exl3p, codebook 2 = mul1): route, gate|up (+ SwiGLU, down's input rotation), down, and
/// slot_sum16 (TF_EXL3_PROMPT_DET=slots16's slot-order sum).
pub const pe_route_symbol = "_ZN8tf_exl3p12route_kernelEPKiiiPiS2_S2_ii";
pub const pe_gateup_symbol = "_ZN8tf_exl3p20prompt_gateup_kernelILi2EEEvPK13__nv_bfloat16iPKiS5_S5_PKlS7_S5_PK6__halfSA_SA_SA_SA_PS8_iiiifiP6float4x";
pub const pe_down_symbol = "_ZN8tf_exl3p18prompt_down_kernelILi2EEEvPK6__halfPKiS5_S5_PKlS5_S3_PKfPfiiiii";
pub const pe_slot_sum16_symbol = "_Z17slot_sum16_kernelPK5uint2PKiP6float4xiii";
/// prompt_experts.py PROMPT_K2: the widths its kernels take (2, 3 and 4 bits a value)
pub const prompt_k2s = [_]usize{ 4, 6, 8 };
/// prompt_experts.py CHUNK_ROWS / SLAB_BYTES
pub const pe_chunk_rows: usize = 4096;
pub const pe_slab_bytes: usize = 9 << 20;

/// prompt_experts.auto_ncb: column blocks (of 256) a down pass - the widest slab of out within SLAB_BYTES.
pub fn autoNcb(R: usize, D: usize, elem: usize) usize {
    const blocks = D / 256;
    var best: usize = 1;
    var d: usize = 1;
    while (d <= blocks) : (d += 1) {
        if (blocks % d == 0 and R * d * 256 * elem <= pe_slab_bytes) best = d;
    }
    return best;
}

/// x3prefill.tiles: (rows a program, K step, warps, stages, row blocks a raster group) for a K x N prompt GEMM.
pub const PrefillTiles = struct { bm: usize, bk: usize, warps: u32, stages: u32, group: usize };
pub fn prefillTiles(k: usize, n: usize) PrefillTiles {
    const T = struct { k: usize, n: usize, t: PrefillTiles };
    const tuned = [_]T{
        .{ .k = 2048, .n = 4096, .t = .{ .bm = 128, .bk = 64, .warps = 8, .stages = 4, .group = 8 } },
        .{ .k = 6144, .n = 3072, .t = .{ .bm = 64, .bk = 64, .warps = 8, .stages = 4, .group = 8 } },
        .{ .k = 3072, .n = 6144, .t = .{ .bm = 128, .bk = 64, .warps = 8, .stages = 3, .group = 8 } },
        .{ .k = 6144, .n = 512, .t = .{ .bm = 64, .bk = 64, .warps = 4, .stages = 4, .group = 8 } },
        .{ .k = 6144, .n = 640, .t = .{ .bm = 128, .bk = 64, .warps = 8, .stages = 4, .group = 8 } },
        .{ .k = 6144, .n = 2048, .t = .{ .bm = 128, .bk = 64, .warps = 8, .stages = 4, .group = 8 } },
        .{ .k = 512, .n = 6144, .t = .{ .bm = 128, .bk = 64, .warps = 8, .stages = 4, .group = 8 } },
        .{ .k = 4096, .n = 6144, .t = .{ .bm = 128, .bk = 64, .warps = 8, .stages = 3, .group = 8 } },
    };
    for (tuned) |x| if (x.k == k and x.n == n) return x.t;
    return .{ .bm = 128, .bk = 32, .warps = 8, .stages = 4, .group = 8 };
}

/// x3prefill.HAD_SCALE (1 / sqrt(128)) as the fp32 constexpr Triton compiled.
pub const had_scale: f32 = @floatCast(@as(f64, 0.08838834764831845));

test "prompt experts' column slabs (prompt_experts.auto_ncb)" {
    try std.testing.expectEqual(@as(usize, 2), autoNcb(4096, 6144, 4)); // 4096 x 256 x 4 = 4 MiB a block, 9 MiB a slab
    try std.testing.expectEqual(@as(usize, 4), autoNcb(2048, 6144, 4));
    try std.testing.expectEqual(@as(usize, 24), autoNcb(16, 6144, 4));
}

test "the prompt GEMM's tiles and the weight decode's symbol" {
    try std.testing.expectEqual(PrefillTiles{ .bm = 64, .bk = 64, .warps = 8, .stages = 4, .group = 8 }, prefillTiles(6144, 3072));
    try std.testing.expectEqual(PrefillTiles{ .bm = 128, .bk = 32, .warps = 8, .stages = 4, .group = 8 }, prefillTiles(6144, 4096));
    var buf: [128]u8 = undefined;
    try std.testing.expectEqualStrings("_ZN14tf_exl3_linear13unpack_kernelILi10ELi2EEEvPKjP6__halfill", try unpackSymbol(&buf, 10, .mul1));
    try std.testing.expectEqual(@as(u32, 0x3db504f3), @as(u32, @bitCast(had_scale)));
}

test "x3linear.plan for GLM-5.3's dense shapes at world 1 and per rank of world 4" {
    const T = struct { k: usize, n: usize, want: [2]usize };
    const cases = [_]T{
        .{ .k = 6144, .n = 2048, .want = .{ 8, 4 } }, // q_a, shared expert gate/up
        .{ .k = 6144, .n = 640, .want = .{ 8, 4 } }, // kv_a (640 stored outputs)
        .{ .k = 2048, .n = 16384, .want = .{ 1, 8 } }, // q_b
        .{ .k = 2048, .n = 4096, .want = .{ 4, 4 } }, // indexer wq_b
        .{ .k = 16384, .n = 6144, .want = .{ 4, 4 } }, // o_proj
        .{ .k = 6144, .n = 12288, .want = .{ 1, 8 } }, // dense gate/up
        .{ .k = 12288, .n = 6144, .want = .{ 4, 4 } }, // dense down
        .{ .k = 2048, .n = 6144, .want = .{ 4, 4 } }, // shared expert down
        // one rank of world 4 (Phase 1 and serving): 16 heads, quarter MLP / expert widths
        .{ .k = 2048, .n = 4096, .want = .{ 4, 4 } }, // q_b (16 heads x 256)
        .{ .k = 4096, .n = 6144, .want = .{ 4, 4 } }, // o_proj
        .{ .k = 6144, .n = 3072, .want = .{ 8, 4 } }, // dense gate/up
        .{ .k = 3072, .n = 6144, .want = .{ 4, 4 } }, // dense down
        .{ .k = 6144, .n = 512, .want = .{ 8, 4 } }, // shared expert gate/up
        .{ .k = 512, .n = 6144, .want = .{ 1, 4 } }, // shared expert down
    };
    for (cases) |c| try std.testing.expectEqual(c.want, plan(c.k, c.n));
}

test "strips puts each 128-column block's tiles in k order" {
    // K = 32 (2 k tiles), N = 256 (16 n tiles, 2 blocks), 1 byte a tile: byte = 100 * kt + nt
    var in: [2 * 16]u8 = undefined;
    for (0..2) |i| for (0..16) |j| {
        in[i * 16 + j] = @intCast(100 * i + j);
    };
    var out: [32]u8 = undefined;
    strips(&out, &in, 32, 256, 1);
    // block 0: kt 0 tiles 0..7, kt 1 tiles 0..7; block 1: kt 0 tiles 8..15, kt 1 tiles 8..15
    try std.testing.expectEqualSlices(u8, &.{ 0, 1, 2, 3, 4, 5, 6, 7, 100, 101, 102, 103, 104, 105, 106, 107 }, out[0..16]);
    try std.testing.expectEqualSlices(u8, &.{ 8, 9, 10, 11, 12, 13, 14, 15, 108, 109, 110, 111, 112, 113, 114, 115 }, out[16..32]);
}

test "grouping, tiles and symbols follow the Python launchers" {
    const a: Linear = .{ .words = 0, .suh = 0, .svh = 0, .counters = 0, .k = 6144, .n = 2048, .k2 = 10, .cb = .mul1, .sk = 8, .wk = 4 };
    var b = a;
    b.n = 640;
    var c = a;
    c.k = 2048;
    try std.testing.expect(groupable(&.{ &a, &b }));
    try std.testing.expect(!groupable(&.{ &a, &c }));
    var d = a;
    d.wk = 8;
    try std.testing.expect(!groupable(&.{ &a, &d }));
    try std.testing.expectEqual(glm_gateup, try defaultTiles(6144, 2048, true));
    try std.testing.expectEqual(glm_down, try defaultTiles(2048, 6144, false));
    try std.testing.expectEqual([2]usize{ 2, 10 }, k2Range(4, 8));
    try std.testing.expectEqual([2]usize{ 8, 8 }, k2Range(8, 8));
    try std.testing.expect(vecOk(10) and !vecOk(4) and !vecOk(14));
    var buf: [256]u8 = undefined;
    try std.testing.expectEqualStrings("_ZN14tf_exl3_linear13linear_kernelILi10ELi2ELi4ELi1ELi1EEEvNS_4JobsEii", try linearSymbol(&buf, 10, .mul1, 4, 1, true));
    try std.testing.expectEqualStrings("_ZN8tf_exl3x14grouped_kernelILi2ELi8ELi4ELi1ELi1ELi2ELi10EEEvPK6__halfS3_PKlS5_PKiS7_S7_S7_S7_PfiiiiiiiNS_3EpiE", try groupedSymbol(&buf, .mul1, 2, 10));
    try std.testing.expectEqual(@as(usize, 32768), linearSmem(8, 24, 10, true));
    const s = a.strides();
    try std.testing.expectEqual(@as(i64, 320), s[0]);
    try std.testing.expectEqual(@as(i64, 384 * 320), s[1]);
}
