#!/usr/bin/env python3
"""Device-only copies of GLM-5.3's EXL3 CUDA kernels for the Zig build (nvcc -fatbin, no ATen, no torch).

From the Python engine's src/tensorfold/cuda/exl3/{linear.cu, experts.cu, experts_grouped.cuh, decode.cuh}:

* zig/kernels/cuda/glm53/decode.cuh            verbatim (it has no ATen)
* zig/kernels/cuda/glm53/experts_grouped.cuh   the device part (ATen includes, launch_ex and the host launchers cut)
* zig/kernels/cuda/glm53_exl3_linear.cu        linear.cu's device part, its anonymous namespace named tf_exl3_linear
                                               (kernels need a stable symbol), plus the explicit instantiations below
* zig/kernels/cuda/glm53_exl3_experts.cu       experts.cu's device kernels (namespace tf_exl3x_k) plus the grouped
                                               kernel instantiations GLM-5.3's decode windows launch
* zig/kernels/cuda/glm53_prompt_experts.cu     prompt_experts.cu's device part (Phase 3a: namespace tf_exl3p, the
                                               codebook-2 gate|up / down instantiations, a launch-constants kernel);
                                               linear.cu's copy also gains WK 2 and the unpack_kernel instantiations

Only text moves: every kernel body is the Python build's, so tests/cuda/nemotron/sass_compare.py-style checks against
the Python extension's .cuda.o can prove the SASS. ``--check`` compares instead of writing (exit 1 on drift).
Usage: python3 -B tools/glm53/copy_exl3_kernels.py --src <champion src>/src/tensorfold/cuda/exl3 [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "zig" / "kernels" / "cuda"

# linear_kernel<K2, CB, WK, G, V>: GLM-5.3's dense linears are 5-bit mul1 (K2 10, CB 2); the 2.75 bpw mixed-K pack
# also has 3/4-bit (K2 6/8) dense parts in other packs. WK from x3linear.plan (4 or 8), G 1 (<= 8 rows) or 2, V = vec_ok.
LINEAR_K2 = (6, 8, 10, 16)   # 16: the MTP layer's 8-bit dense projections (layer 78)
LINEAR_CB = (2,)
# warps a block: x3linear.plan picks 4 or 8; Phase 3a's served tiles (fused.tune_linears / tune_groups, saved with
# TF_GLM53_TILES=save:) may also pick 2
LINEAR_WK = (2, 4, 8)
# grouped_kernel<CB, NT, W, PF, V, LO, HI> with GLM's tiles (8 n tiles, 4 warps), 16-byte loads (V 1, PF 1) and every
# K2 range the launcher picks
EXPERT_RANGES = ((8, 8), (2, 10), (2, 16))


def vec_ok(k2: int) -> int:
    return int(not (k2 in (2, 4)) and k2 <= 12)


def strip_includes(lines: list[str]) -> list[str]:
    """ATen / c10 includes cut; <cstdint> added (torch's headers brought uint32_t / int64_t in transitively)."""
    kept = [ln for ln in lines if not ln.startswith(("#include <ATen", "#include <c10"))]
    return (["#include <cstdint>"] if "#include <cstdint>" not in kept else []) + kept


def linear_cu(src: str) -> str:
    lines = strip_includes(src.splitlines())
    out, named = [], False
    for ln in lines:
        if ln.startswith("int dtype_of(const at::Tensor& t)"):
            break
        if ln == '#include "decode.cuh"':
            ln = '#include "glm53/decode.cuh"'
        if ln == "namespace {" and not named:
            ln, named = "namespace tf_exl3_linear {", True
        out.append(ln)
    else:
        raise SystemExit("linear.cu: the host part's first line (dtype_of) was not found")
    if not named:
        raise SystemExit("linear.cu: no anonymous namespace")
    head = ["// Device code of src/tensorfold/cuda/exl3/linear.cu (up to dtype_of; ATen includes and the host launchers "
            "dropped,", "// the anonymous namespace named), generated by tools/glm53/copy_exl3_kernels.py: do not edit.",
            ""]
    inst = ["}  // namespace tf_exl3_linear", "",
            "// rot_in_kernel and the linear_kernel instantiations GLM-5.3's dense EXL3 linears launch (loads 35:",
            "// transposed walk, 16-byte weight loads where vec_ok, PDL).",
            "template __global__ void tf_exl3_linear::linear_kernel<%d, %d, %d, %d, %d>(const __grid_constant__ "
            "tf_exl3_linear::Jobs, int, int);"]
    lines_inst = []
    for k2 in LINEAR_K2:
        for cb in LINEAR_CB:
            for wk in LINEAR_WK:
                for g in (1, 2):
                    lines_inst.append(inst[-1] % (k2, cb, wk, g, vec_ok(k2)))
    # Phase 3a: the prompt GEMM's weight decode (x3prefill.matmul -> ext.unpack, fp16 W_q [K, N])
    unpack = ["", "// unpack_kernel instantiations x3prefill.matmul launches (W_q decoded once a prompt chunk)."]
    for k2 in LINEAR_K2:
        for cb in LINEAR_CB:
            unpack.append(f"template __global__ void tf_exl3_linear::unpack_kernel<{k2}, {cb}>(const uint32_t*, half*, "
                          "int, int64_t, int64_t);")
    return "\n".join(head + out + inst[:-1] + lines_inst + unpack) + "\n"


def grouped_cuh(src: str) -> str:
    lines = strip_includes(src.splitlines())
    out, skip = [], False
    i = 0
    while i < len(lines):
        ln = lines[i]
        # launch_ex: a host template (cudaLaunchKernelEx + C10_CUDA_CHECK) up to its closing brace
        if ln.startswith("template <typename... KArgs, typename... Args>"):
            j = i
            while lines[j] != "}":
                j += 1
            i = j + 1
            continue
        # struct GroupedArgs and the host launchers after it: everything up to the namespace's end
        if ln.startswith("struct GroupedArgs {"):
            skip = True
        if skip and ln.startswith("}  // namespace tf_exl3x"):
            skip = False
        if not skip:
            out.append(ln)
        i += 1
    if "launch_ex" in "\n".join(out) or "TORCH_CHECK" in "\n".join(out):
        raise SystemExit("experts_grouped.cuh: host code left in the device copy")
    head = ["// Device part of src/tensorfold/cuda/exl3/experts_grouped.cuh (ATen includes, launch_ex, GroupedArgs and "
            "the host", "// launchers dropped), generated by tools/glm53/copy_exl3_kernels.py: do not edit."]
    return "\n".join(head + out) + "\n"


def experts_cu(src: str) -> str:
    lines = strip_includes(src.splitlines())
    out, named = [], False
    for ln in lines:
        if ln.startswith("// ----------------------------------------"):
            break
        if ln == "using tf_exl3x::launch_ex;":           # a host template, not in the device copy
            continue
        if ln == '#include "experts_grouped.cuh"':
            ln = '#include "glm53/experts_grouped.cuh"'
        if ln == "namespace {" and not named:
            ln, named = "namespace tf_exl3x_k {", True
        out.append(ln)
    else:
        raise SystemExit("experts.cu: the host part's separator was not found")
    while out and out[-1].strip() == "":
        out.pop()
    if not out or not out[-1].startswith("}  // namespace"):
        raise SystemExit("experts.cu: the device part does not end with its namespace")
    out[-1] = "}  // namespace tf_exl3x_k"
    head = ["// Device kernels of src/tensorfold/cuda/exl3/experts.cu (ATen includes and host launchers dropped, the "
            "anonymous", "// namespace named) and the grouped kernels of experts_grouped.cuh GLM-5.3's decode windows "
            "launch,", "// generated by tools/glm53/copy_exl3_kernels.py: do not edit.", ""]
    inst = ["", "// GLM's expert tiles (8 n tiles, 4 warps), 16-byte trellis loads one k step ahead (TF_EXL3_EXPERTS_LOADS 1),",
            "// mul1 (codebook 2), every K2 range grouped_launch picks."]
    for lo, hi in EXPERT_RANGES:
        inst.append(f"template __global__ void tf_exl3x::grouped_kernel<2, 8, 4, 1, 1, {lo}, {hi}>(const half*, "
                    "const half*, const int64_t*, const int64_t*, const int*, const int*, const int*, const int*, "
                    "const int*, float*, int, int, int, int, int, int, int, const tf_exl3x::Epi);")
    inst.append("template __global__ void tf_exl3x_k::rot_in_kernel<__nv_bfloat16>(const __nv_bfloat16*, int, "
                "const int*, const half*, const half*, half*, half*, int, int, int);")
    return "\n".join(head + out + inst) + "\n"


def prompt_experts_cu(src: str) -> str:
    """prompt_experts.cu's device part (Phase 3a: the served prompt path's routed experts): ATen includes and the host
    launchers cut (launch_cb, the exl3p_*_cuda functions), the anonymous namespace named tf_exl3p (kernels need a
    stable symbol), the codebook-2 (mul1) instantiations of the two templated kernels, and a constants kernel the Zig
    launcher reads its dynamic shared memory sizes from."""
    lines = strip_includes(src.splitlines())
    out, named, skip, host = [], False, False, False
    for ln in lines:
        if ln == '#include "experts_grouped.cuh"':
            ln = '#include "glm53/experts_grouped.cuh"'
        if ln == "namespace {" and not named:
            ln, named = "namespace tf_exl3p {", True
        if ln.startswith("void launch_cb("):          # the host launcher; its "template <int CB>" line is out[-1]
            if not out or out[-1] != "template <int CB>":
                raise SystemExit("prompt_experts.cu: launch_cb without its template line")
            out.pop()
            skip = True
            continue
        if skip:
            if ln == "}  // namespace":
                skip = False
                out.append("}  // namespace tf_exl3p")
                out.append("")
                out.append("using namespace tf_exl3p;   // FIX_BITS for the kernels below")
            continue
        if host:                                      # a host function after the namespace: up to its closing brace
            if ln == "}":
                host = False
            continue
        if ln.startswith(("void exl3p_", "int64_t exl3p_")):
            host = not ln.rstrip().endswith("}")
            continue
        out.append(ln)
    if not named or skip or host:
        raise SystemExit("prompt_experts.cu: the namespace / host part did not parse")
    text = "\n".join(out)
    if "at::" in text or "C10_" in text or "TORCH_CHECK" in text:
        raise SystemExit("prompt_experts.cu: host code left in the device copy")
    while out and out[-1].strip() == "":
        out.pop()
    head = ["// Device code of src/tensorfold/cuda/exl3/prompt_experts.cu (ATen includes and the host launchers dropped, "
            "the", "// anonymous namespace named tf_exl3p), generated by tools/glm53/copy_exl3_kernels.py: do not edit.",
            ""]
    inst = ["", "// the codebook-2 (mul1) kernels GLM-5.3's prompt chunks launch (SharedExperts.prefill -> prompt_routed)",
            "template __global__ void tf_exl3p::prompt_gateup_kernel<2>(const __nv_bfloat16*, int, const int*, "
            "const int*, const int*, const int64_t*, const int64_t*, const int*, const half*, const half*, const half*, "
            "const half*, const half*, half*, int, int, int, int, float, int, float4*, long long);",
            "template __global__ void tf_exl3p::prompt_down_kernel<2>(const half*, const int*, const int*, const int*, "
            "const int64_t*, const int*, const half*, const float*, float*, int, int, int, int, int);",
            "",
            "// the launch constants prompt_experts.cpp's launch_cb uses: GU_SMEM, DN_SMEM, GU_THREADS, NTHREADS, IPM",
            'extern "C" __global__ void glm53_pe_consts(int* out) {',
            "    out[0] = (int)tf_exl3p::GU_SMEM;",
            "    out[1] = (int)tf_exl3p::DN_SMEM;",
            "    out[2] = tf_exl3p::GU_THREADS;",
            "    out[3] = tf_exl3p::NTHREADS;",
            "    out[4] = tf_exl3p::IPM;",
            "}"]
    return "\n".join(head + out + inst) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", required=True, help="the Python engine's src/tensorfold/cuda/exl3")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    src = Path(a.src)
    files = {
        OUT / "glm53" / "decode.cuh": (src / "decode.cuh").read_text(),
        OUT / "glm53" / "experts_grouped.cuh": grouped_cuh((src / "experts_grouped.cuh").read_text()),
        OUT / "glm53_exl3_linear.cu": linear_cu((src / "linear.cu").read_text()),
        OUT / "glm53_exl3_experts.cu": experts_cu((src / "experts.cu").read_text()),
        OUT / "glm53_prompt_experts.cu": prompt_experts_cu((src / "prompt_experts.cu").read_text()),
    }
    bad = 0
    for path, text in files.items():
        if a.check:
            if not path.exists() or path.read_text() != text:
                print(f"DRIFT {path.relative_to(REPO)}")
                bad = 1
            else:
                print(f"same  {path.relative_to(REPO)}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"wrote {path.relative_to(REPO)} ({text.count(chr(10))} lines)")
    return bad


if __name__ == "__main__":
    sys.exit(main())
