// Device part of src/tensorfold/cuda/exl3/experts_grouped.cuh (ATen includes, launch_ex, GroupedArgs and the host
// launchers dropped), generated by tools/glm53/copy_exl3_kernels.py: do not edit.
#include <cstdint>
// Grouped EXL3 expert GEMV (after ExLlamaV3, MIT, Copyright (c) 2025 Turboderp): rows stay independent, K ranges fixed by shape, warps summed in order.
#pragma once

#include <cuda_fp16.h>
#include <cuda_bf16.h>
#include <utility>

namespace tf_exl3x {

// Two codebook values (CB 0 3inst, 1 mcg, 2 mul1) as a half2, bit-identical to ExLlamaV3's decode_3inst_2<cb>.
template <int CB>
__device__ __forceinline__ uint32_t cb_pair(uint32_t s0, uint32_t s1) {
    if constexpr (CB == 2) {
        const uint32_t x0 = s0 * 0x83DCD12Du, x1 = s1 * 0x83DCD12Du;
        const uint32_t sum0 = __dp4a(x0, 0x01010101u, 0x6400u);
        const uint32_t sum1 = __dp4a(x1, 0x01010101u, 0x6400u);
        const uint32_t hv = __byte_perm(sum0, sum1, 0x5410);
        half2 h = *reinterpret_cast<const half2*>(&hv);
        half2 r = __hfma2(h, __half2half2(__ushort_as_half(0x1eee)), __half2half2(__ushort_as_half(0xc931)));
        return *reinterpret_cast<uint32_t*>(&r);
    } else {
        uint32_t x0, x1;
        if constexpr (CB == 1) {
            x0 = s0 * 0xCBAC1FEDu;
            x1 = s1 * 0xCBAC1FEDu;
        } else {
            x0 = s0 * 89226354u + 64248484u;
            x1 = s1 * 89226354u + 64248484u;
        }
        x0 = (x0 & 0x8FFF8FFFu) ^ 0x3B603B60u;
        x1 = (x1 & 0x8FFF8FFFu) ^ 0x3B603B60u;
        uint32_t lo = __byte_perm(x0, x1, 0x5410);
        uint32_t hi = __byte_perm(x0, x1, 0x7632);
        half2 r = __hadd2(*reinterpret_cast<half2*>(&lo), *reinterpret_cast<half2*>(&hi));
        return *reinterpret_cast<uint32_t*>(&r);
    }
}

// K2 half-bits a value: a tile is 4 * K2 words; a lane's eight windows fall in NG runs of GV within two words.
template <int K2>
struct Fmt {
    static constexpr int TW = 4 * K2;
    static constexpr int LW = (TW + 31) / 32;
    // windows sharing one 64-bit merge (tests/cuda/test_exl3_experts.py checks every K2)
    static constexpr int GV = (K2 >= 13) ? 2 : ((K2 == 7 || (K2 >= 9 && K2 <= 12) || K2 == 16) ? 4 : 8);
    static constexpr int NG = 8 / GV;
    __host__ __device__ static constexpr int end(int p) { return (p >> 1) * K2 + ((p & 1) ? K2 : (K2 >> 1)); }
    // right shift of window j of a run (run starts at an even position) relative to the run's last window
    __host__ __device__ static constexpr int off(int j) { return end(GV - 1) - end(j); }
};

template <int K2>
struct LaneMap {
    int hi[Fmt<K2>::NG], lo[Fmt<K2>::NG], sh[Fmt<K2>::NG];
    __device__ __forceinline__ explicit LaneMap(int lane) {
        constexpr int TW = Fmt<K2>::TW, GV = Fmt<K2>::GV;
#pragma unroll
        for (int g = 0; g < Fmt<K2>::NG; ++g) {
            const int last_end = Fmt<K2>::end(8 * lane + g * GV + GV - 1) + 128 * K2;
            const int hr = (last_end - 1) >> 5;
            hi[g] = hr % TW;
            lo[g] = (hr + TW - 1) % TW;
            sh[g] = (hr + 1) * 32 - last_end;
        }
    }
};

template <int LW>
__device__ __forceinline__ uint32_t fetch(const uint32_t (&w)[LW], int idx) {
    if constexpr (LW == 1) {
        return __shfl_sync(0xffffffffu, w[0], idx);
    } else {
        const uint32_t a = __shfl_sync(0xffffffffu, w[0], idx & 31);
        const uint32_t b = __shfl_sync(0xffffffffu, w[1], idx & 31);
        return idx < 32 ? a : b;
    }
}

// This lane's eight values of a tile as the B fragments of its two n8 halves.
template <int CB, int K2>
__device__ __forceinline__ void decode_tile(const uint32_t (&w)[Fmt<K2>::LW], const LaneMap<K2>& m, int lane,
                                            uint32_t (&b0)[2], uint32_t (&b1)[2]) {
    uint32_t st[8];
    if constexpr (K2 == 8) {
        // 4 bits: lane L's windows are exactly words L-1 and L (the GLM kernel's decode)
        const uint32_t p = __shfl_sync(0xffffffffu, w[0], (lane + 31) & 31);
        const uint32_t s = __funnelshift_r(w[0], p, 20);
        st[0] = (s >> 8) & 0xffffu;
        st[1] = (s >> 4) & 0xffffu;
        st[2] = s & 0xffffu;
        st[3] = w[0] >> 16;
        st[4] = (w[0] >> 12) & 0xffffu;
        st[5] = (w[0] >> 8) & 0xffffu;
        st[6] = (w[0] >> 4) & 0xffffu;
        st[7] = w[0] & 0xffffu;
    } else {
        constexpr int GV = Fmt<K2>::GV, NG = Fmt<K2>::NG;
#pragma unroll
        for (int g = 0; g < NG; ++g) {
            const uint32_t whi = fetch<Fmt<K2>::LW>(w, m.hi[g]);
            const uint32_t wlo = fetch<Fmt<K2>::LW>(w, m.lo[g]);
            const uint64_t mm = ((((uint64_t)wlo) << 32) | whi) >> m.sh[g];
#pragma unroll
            for (int j = 0; j < GV; ++j) st[g * GV + j] = (uint32_t)(mm >> Fmt<K2>::off(j)) & 0xffffu;
        }
    }
    b0[0] = cb_pair<CB>(st[0], st[1]);
    b0[1] = cb_pair<CB>(st[2], st[3]);
    b1[0] = cb_pair<CB>(st[4], st[5]);
    b1[1] = cb_pair<CB>(st[6], st[7]);
}

__device__ __forceinline__ void mma16816(float (&d)[4], const uint32_t (&a)[4], const uint32_t (&b)[2]) {
    asm volatile("mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32 {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, "
                 "{%0,%1,%2,%3};\n"
                 : "+f"(d[0]), "+f"(d[1]), "+f"(d[2]), "+f"(d[3])
                 : "r"(a[0]), "r"(a[1]), "r"(a[2]), "r"(a[3]), "r"(b[0]), "r"(b[1]));
}

__device__ __forceinline__ uint32_t load_pair(const half* x, bool ok) {
    return ok ? *reinterpret_cast<const uint32_t*>(x) : 0u;
}

// 16 bytes of trellis words, read once a window and not kept in L1 (linear.cu's ldg_nc_v4); asm volatile keeps each
// load where it stands relative to the (volatile) mma, so the depth in flight is what the code says.
__device__ __forceinline__ uint4 ldg_nc_v4(const uint32_t* p) {
    uint4 v;
    asm volatile("ld.global.nc.L1::no_allocate.v4.u32 {%0,%1,%2,%3}, [%4];"
                 : "=r"(v.x), "=r"(v.y), "=r"(v.z), "=r"(v.w)
                 : "l"(p));
    return v;
}

template <int K2>
__device__ __forceinline__ void load_words(uint32_t (&dst)[Fmt<K2>::LW], const uint32_t* p, int lane) {
    constexpr int TW = Fmt<K2>::TW;
#pragma unroll
    for (int l = 0; l < Fmt<K2>::LW; ++l) {
        if constexpr ((TW % 32) == 0)
            dst[l] = __ldg(p + l * 32);
        else
            dst[l] = (l * 32 + lane < TW) ? __ldg(p + l * 32) : 0u;
    }
}

// One warp's k tiles [kt0, kt0 + nkt) of an expert matrix into acc, PF tiles in flight.
template <int CB, int K2, int NT, int PF>
__device__ __forceinline__ void warp_tiles(const uint32_t* __restrict__ T, int NTILES, int kt0, int nkt, int nt0,
                                           const half* x0, const half* x1, bool ok0, bool ok1, int lane,
                                           float (&acc)[NT][2][4]) {
    constexpr int TW = Fmt<K2>::TW, LW = Fmt<K2>::LW;
    const LaneMap<K2> map(lane);
    const size_t kstride = (size_t)NTILES * TW;
    const uint32_t* tp = T + ((size_t)kt0 * NTILES + nt0) * TW + lane;

    uint32_t pf[PF][NT][LW];
#pragma unroll
    for (int d = 0; d < PF; ++d)
        if (d < nkt)
#pragma unroll
            for (int i = 0; i < NT; ++i) load_words<K2>(pf[d][i], tp + d * kstride + i * TW, lane);

    for (int ib = 0; ib < nkt; ib += PF) {
#pragma unroll
        for (int d = 0; d < PF; ++d) {
            const int it = ib + d;
            if (it < nkt) {
                uint32_t w[NT][LW];
#pragma unroll
                for (int i = 0; i < NT; ++i)
#pragma unroll
                    for (int l = 0; l < LW; ++l) w[i][l] = pf[d][i][l];
                if (it + PF < nkt)
#pragma unroll
                    for (int i = 0; i < NT; ++i)
                        load_words<K2>(pf[d][i], tp + (size_t)(it + PF) * kstride + i * TW, lane);
                const int k = (kt0 + it) * 16;
                uint32_t a[4] = {load_pair(x0 + k, ok0), load_pair(x1 + k, ok1), load_pair(x0 + k + 8, ok0),
                                 load_pair(x1 + k + 8, ok1)};
#pragma unroll
                for (int i = 0; i < NT; ++i) {
                    uint32_t b0[2], b1[2];
                    decode_tile<CB, K2>(w[i], map, lane, b0, b1);
                    mma16816(acc[i][0], a, b0);
                    mma16816(acc[i][1], a, b1);
                }
            }
        }
    }
}

// warp_tiles with the trellis words as 16-byte non-coherent loads V k steps ahead (TF_EXL3_EXPERTS_LOADS 1..4;
// after MiaAI-Lab patch 0047 / jayleaton/glm53-tensorfold-spark patch 0580, Apache-2.0). A k step's NT tiles are
// contiguous (NT * TW words from tile (kt, nt0)), so the warp loads the step as whole 16-byte pieces (lane l: pieces
// l, l + 32, ..), stages it in its own slice of shared memory (``stage``, at least NT * TW words, 16-byte aligned)
// and each lane reads back exactly the words load_words gives it. Every decode, mma and sum is warp_tiles' in the
// same order: the same bits. Needs 16-byte aligned trellises (prepare() checks; routed() falls back to 32-bit loads).
template <int CB, int K2, int NT, int V>
__device__ __forceinline__ void warp_tiles_v(const uint32_t* __restrict__ T, int NTILES, int kt0, int nkt, int nt0,
                                             const half* x0, const half* x1, bool ok0, bool ok1, int lane,
                                             uint32_t* stage, float (&acc)[NT][2][4]) {
    constexpr int TW = Fmt<K2>::TW, LW = Fmt<K2>::LW;
    constexpr int CH = NT * TW / 4;                       // 16-byte pieces of a k step
    constexpr int NV = (CH + 31) / 32;                    // pieces a lane
    static_assert(V >= 1 && V <= 4, "1 to 4 k steps ahead");
    const LaneMap<K2> map(lane);
    const size_t kstride = (size_t)NTILES * TW;
    const uint32_t* sp = T + ((size_t)kt0 * NTILES + nt0) * TW;

    uint4 rv[V][NV];                                      // ring: step it in rv[it % V]
    auto load_step = [&](int it, uint4 (&v)[NV]) {
        const uint32_t* p = sp + (size_t)it * kstride;
#pragma unroll
        for (int c = 0; c < NV; ++c)
            if (CH % 32 == 0 || c * 32 + lane < CH) v[c] = ldg_nc_v4(p + 4 * (c * 32 + lane));
    };
#pragma unroll
    for (int d = 0; d < V; ++d)
        if (d < nkt) load_step(d, rv[d]);

    for (int ib = 0; ib < nkt; ib += V) {
#pragma unroll
        for (int d = 0; d < V; ++d) {
            const int it = ib + d;
            if (it < nkt) {
                __syncwarp();                             // every lane has read the previous step back
#pragma unroll
                for (int c = 0; c < NV; ++c)
                    if (CH % 32 == 0 || c * 32 + lane < CH)
                        *reinterpret_cast<uint4*>(stage + 4 * (c * 32 + lane)) = rv[d][c];
                if (it + V < nkt) load_step(it + V, rv[d]);   // the slot's registers are free again
                __syncwarp();
                uint32_t w[NT][LW];
#pragma unroll
                for (int i = 0; i < NT; ++i)
#pragma unroll
                    for (int l = 0; l < LW; ++l)
                        w[i][l] = ((TW % 32) == 0 || l * 32 + lane < TW) ? stage[i * TW + l * 32 + lane] : 0u;
                const int k = (kt0 + it) * 16;
                uint32_t a[4] = {load_pair(x0 + k, ok0), load_pair(x1 + k, ok1), load_pair(x0 + k + 8, ok0),
                                 load_pair(x1 + k + 8, ok1)};
#pragma unroll
                for (int i = 0; i < NT; ++i) {
                    uint32_t b0[2], b1[2];
                    decode_tile<CB, K2>(w[i], map, lane, b0, b1);
                    mma16816(acc[i][0], a, b0);
                    mma16816(acc[i][1], a, b1);
                }
            }
        }
    }
    __syncwarp();                                         // the staging slice is the warp's red rows again
}

// ---- the epilogues' arithmetic, one copy for the separate kernels (experts.cu) and the fused ones below ----------

constexpr float HAD_SCALE = 0.08838834764831845f;   // 1 / sqrt(128)

// Walsh-Hadamard transform of 128 values, 4 a lane, fixed butterfly order (strides 1, 2 in registers, 4..64 across lanes).
__device__ __forceinline__ void fwht128(float (&v)[4], int lane) {
    float a = v[0] + v[1], b = v[0] - v[1], c = v[2] + v[3], d = v[2] - v[3];
    v[0] = a + c; v[1] = b + d; v[2] = a - c; v[3] = b - d;
#pragma unroll
    for (int m = 1; m < 32; m <<= 1) {
#pragma unroll
        for (int j = 0; j < 4; ++j) {
            float o = __shfl_xor_sync(0xffffffffu, v[j], m);
            v[j] = (lane & m) ? o - v[j] : v[j] + o;
        }
    }
}

__device__ __forceinline__ float bf16r(float x) { return __bfloat162float(__float2bfloat16_rn(x)); }

// A partial another block of this launch wrote (CG: through L2, after the arrival count) or an earlier kernel did.
template <bool CG>
__device__ __forceinline__ float ld_part(const float* p) {
    if constexpr (CG) return __ldcg(p);
    else return *p;
}

// Pair p's gate/up epilogue on the lane's 4 columns from n (of one 128-column block): the splits summed in order
// from 0, rotated, * svh, SwiGLU (act_mode 0: GLM's bf16 roundings, 1: fp32), then xd = fp16((act * suh_d) @ H).
template <bool CG>
__device__ __forceinline__ void gateup_epi(const float* __restrict__ Z, int p, int e, int n, int P, int N, int SK,
                                           const half* __restrict__ svh_g, const half* __restrict__ svh_u,
                                           const half* __restrict__ suh_d, half* __restrict__ xd, float limit,
                                           int act_mode, int lane) {
    float gv[4], uv[4];
#pragma unroll
    for (int j = 0; j < 4; ++j) {
        float sg = 0.f, su = 0.f;
        for (int s = 0; s < SK; ++s) {
            sg += ld_part<CG>(Z + ((size_t)(0 * SK + s) * P + p) * N + n + j);
            su += ld_part<CG>(Z + ((size_t)(1 * SK + s) * P + p) * N + n + j);
        }
        gv[j] = sg;
        uv[j] = su;
    }
    fwht128(gv, lane);
    fwht128(uv, lane);
    float v[4];
#pragma unroll
    for (int j = 0; j < 4; ++j) {
        float act;
        if (act_mode == 0) {
            float gg = fminf(bf16r(gv[j] * HAD_SCALE * __half2float(svh_g[(size_t)e * N + n + j])), limit);
            float uu = fminf(fmaxf(bf16r(uv[j] * HAD_SCALE * __half2float(svh_u[(size_t)e * N + n + j])), -limit),
                             limit);
            act = bf16r(bf16r(gg / (1.f + expf(-gg))) * uu);
        } else {
            float gg = fminf(gv[j] * HAD_SCALE * __half2float(svh_g[(size_t)e * N + n + j]), limit);
            float uu = fminf(fmaxf(uv[j] * HAD_SCALE * __half2float(svh_u[(size_t)e * N + n + j]), -limit), limit);
            act = gg / (1.f + expf(-gg)) * uu;
        }
        v[j] = act * __half2float(suh_d[(size_t)e * N + n + j]);
    }
    fwht128(v, lane);
    half* o = xd + (size_t)p * N + n;
#pragma unroll
    for (int j = 0; j < 4; ++j) o[j] = __float2half_rn(v[j] * HAD_SCALE);
}

// The down epilogue of a pair's 128 columns from their summed splits v: o = (v @ H) * svh_d (fp32).
__device__ __forceinline__ void down_epi(float (&v)[4], int e, int n, int D, const half* __restrict__ svh_d,
                                         int lane, float (&o)[4]) {
    fwht128(v, lane);
#pragma unroll
    for (int j = 0; j < 4; ++j) o[j] = v[j] * HAD_SCALE * __half2float(svh_d[(size_t)e * D + n + j]);
}

// Row r's combine on 4 columns from n: sum over slots in order of wts[r][q] * y[r * slots + q] (fp32 fma chain
// from 0), the arithmetic of combine_kernel and down_combine_kernel.
template <bool CG>
__device__ __forceinline__ void combine4(const float* __restrict__ y, const float* __restrict__ wts, int r, int slots,
                                         int D, int n, float (&acc)[4]) {
#pragma unroll
    for (int j = 0; j < 4; ++j) acc[j] = 0.f;
    for (int q = 0; q < slots; ++q) {
        const float w = wts[r * slots + q];
        const float* yp = y + ((size_t)r * slots + q) * D + n;
#pragma unroll
        for (int j = 0; j < 4; ++j) acc[j] = fmaf(w, ld_part<CG>(yp + j), acc[j]);
    }
}

// Programmatic dependent launch (no-ops when the launch did not ask for it), as linear.cu: wait for the previous
// kernel's writes (and so, kernel by kernel, every earlier one's) before reading or writing anything but weights; let
// the next PDL kernel launch (it waits in turn for all of this one).
__device__ __forceinline__ void griddep_wait() {
#if defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 900
    asm volatile("griddepcontrol.wait;" ::: "memory");
#endif
}
__device__ __forceinline__ void griddep_launch() {
#if defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 900
    asm volatile("griddepcontrol.launch_dependents;" ::: "memory");
#endif
}


// The fused epilogues of a grouped launch (MiaAI-Lab patch 0016's decode kernel, onto this kernel's settings).
struct Epi {
    int fuse = 0;        // 0: Z partials; 1 (down; SK 1, one matrix): y = its epilogue, and with wts the combine
                         // into out (+ sy); 2 (gate and up): Z, then each (expert, member tile, 128 columns)'s last
                         // block runs the gate/up epilogue into xd. Both need 8 n tiles (one Hadamard block) a program
    const int* pick = nullptr;           // [P] (fuse 1 with wts: the row's routed slots)
    int E = 0;
    const half* svh_g = nullptr;         // fuse 2
    const half* svh_u = nullptr;
    const half* suh_d = nullptr;
    half* xd = nullptr;
    float limit = 0.f;
    int act_mode = 1;
    const half* svh_d = nullptr;         // fuse 1
    float* y = nullptr;                  // [P, D]: routed slots written, the others the caller's
    const float* wts = nullptr;          // [R, slots] or null (no combine)
    float* out = nullptr;                // [R, D]
    const float* sy = nullptr;           // [R, D] added to out (fp32, after the combine) or null
    int* done = nullptr;                 // arrival counts, zero between launches (the last arrival resets its own):
                                         // fuse 2 [grid.x * member tiles * grid.y], fuse 1 with wts [R * grid.y]
};

// The K2 values an instance covering [LO, HI] compiles (half-bits 2..16).
__host__ __device__ constexpr bool k2_supported(int k2) {
    return k2 >= 2 && k2 <= 16;
}

// Program (expert u, n block, split and member tile): up to 16 members times W_q over the split's K range; warps added in order.
// V > 0: warp_tiles_v (16-byte loads V k steps ahead, staged in the warp's slice of red), else warp_tiles (PF tiles).
// ep.fuse 1 / 2: the epilogues fused (Epi); every sum keeps the separate kernels' order, so the outputs keep their bits.
template <int CB, int NT, int W, int PF, int V, int LO, int HI>
__global__ void __launch_bounds__(W * 32) grouped_kernel(
    const half* __restrict__ X0, const half* __restrict__ X1, const int64_t* __restrict__ TP0,
    const int64_t* __restrict__ TP1, const int* __restrict__ K2_0, const int* __restrict__ K2_1,
    const int* __restrict__ uids, const int* __restrict__ ucount, const int* __restrict__ members,
    float* __restrict__ Z, int K, int N, int P, int SK, int maxm, int slots, int NS, const Epi ep) {
    griddep_wait();                                       // the plan, X and the outputs are earlier kernels'
    griddep_launch();
    const int u = blockIdx.x;
    const int warp = threadIdx.x >> 5, lane = threadIdx.x & 31;
    if constexpr (NT == 8) {
        // fused combine: rows without a routed slot get no arrival, so one block a column block combines them
        // (only the caller's y) here, before any early exit
        if (ep.fuse == 1 && ep.wts != nullptr && blockIdx.x == gridDim.x - 1 && blockIdx.z == 0) {
            const int n = blockIdx.y * 128 + 4 * lane;
            for (int r = warp; r < P / slots; r += W) {
                int routed = 0;
                for (int q = 0; q < slots; ++q) {
                    const int pe = ep.pick[r * slots + q];
                    routed += pe >= 0 && pe < ep.E;
                }
                if (routed) continue;
                float acc[4];
                combine4<false>(ep.y, ep.wts, r, slots, N, n, acc);
#pragma unroll
                for (int j = 0; j < 4; ++j)
                    ep.out[(size_t)r * N + n + j] = ep.sy ? __fadd_rn(acc[j], ep.sy[(size_t)r * N + n + j]) : acc[j];
            }
        }
    }
    if (u >= ucount[0]) return;
    const int MT = (maxm + 15) / 16;
    const int mtile = blockIdx.z % MT;
    const int split = (blockIdx.z / MT) % SK;
    const int mat = blockIdx.z / MT / SK;
    const half* X = mat ? X1 : X0;
    const int e = uids[u];
    const uint32_t* T = reinterpret_cast<const uint32_t*>(mat ? TP1[e] : TP0[e]);
    const int k2 = mat ? K2_1[e] : K2_0[e];
    const int g = lane >> 2, t = lane & 3;
    const int KT = K >> 4, NTILES = NS > 0 ? NS : (N >> 4);  // row stride of the trellis, in tiles (gate/up column blocks)

    __shared__ int rows_sh[16];
    if (threadIdx.x < 16) {
        const int m = mtile * 16 + threadIdx.x;
        const int code = m < maxm ? members[u * maxm + m] : -1;
        rows_sh[threadIdx.x] = code >= 0 ? (code >> 5) * slots + (code & 31) : -1;
    }
    __syncthreads();
    if (rows_sh[0] < 0) return;                           // members come first, so this tile is empty
    const int r0 = rows_sh[g], r1 = rows_sh[g + 8];
    const half* x0 = X + (size_t)(r0 < 0 ? 0 : r0) * K + 2 * t;
    const half* x1 = X + (size_t)(r1 < 0 ? 0 : r1) * K + 2 * t;

    const int per_split = KT / SK, per_warp = per_split / W;
    const int kt0 = split * per_split + warp * per_warp;
    const int nt0 = blockIdx.y * NT;

    float acc[NT][2][4];
#pragma unroll
    for (int i = 0; i < NT; ++i)
#pragma unroll
        for (int h = 0; h < 2; ++h)
#pragma unroll
            for (int c = 0; c < 4; ++c) acc[i][h][c] = 0.f;

    // warps' partial sums (below); V > 0 first stages each warp's k steps in its own slice red[warp]
    __shared__ __align__(16) float red[W][16][NT * 16];
    uint32_t* stage = reinterpret_cast<uint32_t*>(&red[warp][0][0]);
    static_assert(NT * 4 * 16 <= 16 * NT * 16, "a k step of the widest tiles fits a warp's slice of red");

    switch (k2) {
#define TF_EXL3X_CASE(K2_)                                                                                      \
    case K2_:                                                                                                   \
        if constexpr (K2_ >= LO && K2_ <= HI) {                                                                 \
            if constexpr (V > 0)                                                                                \
                warp_tiles_v<CB, K2_, NT, V>(T, NTILES, kt0, per_warp, nt0, x0, x1, r0 >= 0, r1 >= 0, lane,     \
                                             stage, acc);                                                       \
            else                                                                                                \
                warp_tiles<CB, K2_, NT, PF>(T, NTILES, kt0, per_warp, nt0, x0, x1, r0 >= 0, r1 >= 0, lane, acc); \
        } else                                                                                                  \
            __trap();                                                                                           \
        break;
        TF_EXL3X_CASE(2)
        TF_EXL3X_CASE(3)
        TF_EXL3X_CASE(4)
        TF_EXL3X_CASE(5)
        TF_EXL3X_CASE(6)
        TF_EXL3X_CASE(7)
        TF_EXL3X_CASE(8)
        TF_EXL3X_CASE(9)
        TF_EXL3X_CASE(10)
        TF_EXL3X_CASE(11)
        TF_EXL3X_CASE(12)
        TF_EXL3X_CASE(13)
        TF_EXL3X_CASE(14)
        TF_EXL3X_CASE(15)
        TF_EXL3X_CASE(16)
#undef TF_EXL3X_CASE
        default:
            __trap();
    }

    // warps' partial sums through shared memory, added in warp order
#pragma unroll
    for (int i = 0; i < NT; ++i)
#pragma unroll
        for (int h = 0; h < 2; ++h) {
            const int col = i * 16 + h * 8 + 2 * t;
            red[warp][g][col] = acc[i][h][0];
            red[warp][g][col + 1] = acc[i][h][1];
            red[warp][g + 8][col] = acc[i][h][2];
            red[warp][g + 8][col + 1] = acc[i][h][3];
        }
    __syncthreads();
    if constexpr (NT == 8) {
        if (ep.fuse == 1) {
            // down (SK 1): down_epilogue on this block's sums, z = 0 + (warps added in order) as its split sum
            const int n = nt0 * 16 + 4 * lane;
            for (int i = warp; i < 16; i += W) {
                const int p = rows_sh[i];
                if (p < 0) continue;
                float v[4], o[4];
#pragma unroll
                for (int j = 0; j < 4; ++j) {
                    float s = red[0][i][4 * lane + j];
#pragma unroll
                    for (int w = 1; w < W; ++w) s += red[w][i][4 * lane + j];
                    float z = 0.f;
                    z += s;
                    v[j] = z;
                }
                down_epi(v, e, n, N, ep.svh_d, lane, o);
#pragma unroll
                for (int j = 0; j < 4; ++j) ep.y[(size_t)p * N + n + j] = o[j];
            }
            if (ep.wts == nullptr) return;
            // the combine: a row's last arriving block (of its routed slots, this column block) sums its slots' y in
            // slot order, as down_combine does, whichever block arrives last
            __shared__ int last_row[16];
            __threadfence();                              // this block's y before its arrivals
            __syncthreads();
            if (threadIdx.x < 16) {
                const int p = rows_sh[threadIdx.x];
                int last = 0;
                if (p >= 0) {
                    const int r = p / slots;
                    int routed = 0;
                    for (int q = 0; q < slots; ++q) {
                        const int pe = ep.pick[r * slots + q];
                        routed += pe >= 0 && pe < ep.E;
                    }
                    int* c = ep.done + (size_t)r * gridDim.y + blockIdx.y;
                    last = atomicAdd(c, 1) == routed - 1;
                    if (last) *c = 0;                     // every arrival is in: the next launch starts from zero
                }
                last_row[threadIdx.x] = last;
            }
            __syncthreads();
            bool fenced = false;
            for (int i = warp; i < 16; i += W) {
                if (!last_row[i]) continue;
                if (!fenced) {
                    __threadfence();                      // every arrival's y is visible from here
                    fenced = true;
                }
                const int r = rows_sh[i] / slots;
                float acc[4];
                combine4<true>(ep.y, ep.wts, r, slots, N, n, acc);
#pragma unroll
                for (int j = 0; j < 4; ++j)
                    ep.out[(size_t)r * N + n + j] = ep.sy ? __fadd_rn(acc[j], ep.sy[(size_t)r * N + n + j]) : acc[j];
            }
            return;
        }
    }
    for (int idx = threadIdx.x; idx < 16 * NT * 16; idx += W * 32) {
        const int row = idx / (NT * 16), col = idx % (NT * 16);
        const int r = rows_sh[row];
        if (r < 0) continue;
        float s = red[0][row][col];
#pragma unroll
        for (int w = 1; w < W; ++w) s += red[w][row][col];
        Z[(((size_t)mat * SK + split) * P + r) * N + nt0 * 16 + col] = s;
    }
    if constexpr (NT == 8) {
        if (ep.fuse == 2) {
            // gate/up: the last of the 2 * SK blocks of (expert, member tile, 128 columns) runs gateup_epilogue on
            // its rows, the partials read in split order: the same sums whichever block arrives last
            __shared__ int last;
            __threadfence();                              // this block's partials before its arrival
            __syncthreads();
            if (threadIdx.x == 0) {
                int* c = ep.done + ((size_t)u * MT + mtile) * gridDim.y + blockIdx.y;
                last = atomicAdd(c, 1) == 2 * SK - 1;
                if (last) *c = 0;
            }
            __syncthreads();
            if (!last) return;
            __threadfence();
            const int n = nt0 * 16 + 4 * lane;
            for (int i = warp; i < 16; i += W) {
                const int p = rows_sh[i];
                if (p < 0) continue;
                gateup_epi<true>(Z, p, e, n, P, N, SK, ep.svh_g, ep.svh_u, ep.suh_d, ep.xd, ep.limit, ep.act_mode,
                                 lane);
            }
        }
    }
}

// W_q [K, N] fp16 of one matrix through the same lane decode (tests; not on the forward path).
template <int CB, int K2>
__global__ void dequant_kernel(const uint32_t* __restrict__ T, half* __restrict__ out, int K, int N) {
    const int kt = blockIdx.x, nt = blockIdx.y, lane = threadIdx.x;
    const int NTILES = N >> 4;
    uint32_t w[Fmt<K2>::LW];
    load_words<K2>(w, T + ((size_t)kt * NTILES + nt) * Fmt<K2>::TW + lane, lane);
    const LaneMap<K2> map(lane);
    uint32_t b0[2], b1[2];
    decode_tile<CB, K2>(w, map, lane, b0, b1);
    const int g = lane >> 2, t = lane & 3;
    uint32_t v[4] = {b0[0], b0[1], b1[0], b1[1]};
#pragma unroll
    for (int q = 0; q < 4; ++q) {
        half2 h = *reinterpret_cast<half2*>(&v[q]);
        const int col = nt * 16 + g + 8 * (q >> 1);
        const int row = kt * 16 + 2 * t + 8 * (q & 1);
        out[(size_t)row * N + col] = __low2half(h);
        out[(size_t)(row + 1) * N + col] = __high2half(h);
    }
}

}  // namespace tf_exl3x
